const lessons = [
  { id:'intro', tag:'CONCEPT', title:'What is an array?', objective:'Understand how arrays store ordered data and how to access each value efficiently.', duration:'12 min lesson', body:`<h3>One shelf, many values</h3><p>An array is a collection of values stored in an ordered sequence. Imagine a row of numbered lockers: each locker has a position, and you can reach a value directly when you know its index.</p><div class="concept-callout"><strong>The key idea</strong><p>Arrays give you fast access by index. In Python, we use a <code>list</code> to represent the array data structure.</p></div><h4>Indexes start at zero</h4><p>The first element lives at index <strong>0</strong>, the second at index <strong>1</strong>, and so on. This is one of the first details to make automatic.</p><pre class="code-snippet"><span class="comment"># index:     0   1   2   3</span>\nmarks = [72, 85, 68, 91]\nprint(marks[0])  <span class="comment"># 72</span>\nprint(marks[3])  <span class="comment"># 91</span></pre><h4>When arrays are useful</h4><ul><li>Storing a sequence of related values.</li><li>Looping through every value in a predictable order.</li><li>Building more advanced patterns such as two pointers and sliding windows.</li></ul>`, code:`numbers = [12, 7, 19, 4]\n\n# Access the first and last values\nprint(numbers[0])\nprint(numbers[-1])`, output:'12\n4', problems:[{id:'largest',title:'Find the largest value',difficulty:'EASY',description:'Write a function that returns the largest number in a non-empty array of integers.',hint:'Start with the first value as your current answer. Compare every next value against it.',functionName:'find_largest',starter:'def find_largest(nums):\n    # Return the largest value\n    pass',examples:'find_largest([4, 9, 2, 7])  →  9\nfind_largest([-3, -1, -8]) → -1',tests:[{args:[[4,9,2,7]],expected:9},{args:[[-3,-1,-8]],expected:-1},{args:[[5]],expected:5}]}]},
  { id:'traverse', tag:'CORE OPERATION', title:'Traverse an array', objective:'Learn how to visit every element using a loop and keep a running result.', duration:'14 min lesson', body:`<h3>Walking through every value</h3><p>Traversal means visiting each element in order. The most common tool is a <code>for</code> loop. Once you can traverse an array, you can count, filter, compare, and accumulate values.</p><div class="concept-callout"><strong>Pattern to remember</strong><p>Initialize an answer before the loop, update it for each element, then return or print the answer after the loop.</p></div><pre class="code-snippet">numbers = [3, 8, 2, 9]\ntotal = 0\n\nfor number in numbers:\n    total += number\n\nprint(total)  <span class="comment"># 22</span></pre><h4>Complexity</h4><p>If an array has <code>n</code> values and we visit each value once, the time complexity is <strong>O(n)</strong>. We are not creating another array, so the extra space is <strong>O(1)</strong>.</p>`, code:`numbers = [3, 8, 2, 9]\ntotal = 0\n\nfor number in numbers:\n    total += number\n\nprint(total)`, output:'22', problems:[{id:'count_even',title:'Count the even numbers',difficulty:'EASY',description:'Return how many values in the array are divisible by 2.',hint:'Use a counter. For each number, check whether number % 2 equals 0.',functionName:'count_even',starter:'def count_even(nums):\n    # Return the count of even values\n    pass',examples:'count_even([1, 2, 4, 7]) → 2\ncount_even([3, 5])          → 0',tests:[{args:[[1,2,4,7]],expected:2},{args:[[3,5]],expected:0},{args:[[2,2,2]],expected:3}]}]},
  { id:'maxmin', tag:'PATTERN', title:'Find max and min', objective:'Use a running answer to find extremes in one pass through an array.', duration:'16 min lesson', body:`<h3>Keep the best answer so far</h3><p>To find the largest value, keep a variable called <code>largest</code>. Whenever you see a value bigger than it, update the variable. The same idea works for the smallest value.</p><pre class="code-snippet">numbers = [12, 7, 19, 4]\nlargest = numbers[0]\n\nfor number in numbers:\n    if number &gt; largest:\n        largest = number\n\nprint(largest)  <span class="comment"># 19</span></pre><div class="concept-callout"><strong>Why not sort first?</strong><p>Sorting would take O(n log n) time. A single scan finds the answer in O(n), which is faster and uses less extra space.</p></div><h4>Edge cases</h4><p>Think about a one-element array and an array containing only negative numbers. Good solutions handle both without special tricks.</p>`, code:`numbers = [12, 7, 19, 4]\nlargest = numbers[0]\n\nfor number in numbers:\n    if number > largest:\n        largest = number\n\nprint(largest)`, output:'19', problems:[{id:'second_largest',title:'Find the second largest',difficulty:'EASY',description:'Return the second largest distinct value in an array containing at least two distinct numbers.',hint:'Track both the largest and second largest values as you scan the array.',functionName:'second_largest',starter:'def second_largest(nums):\n    # Return the second largest distinct value\n    pass',examples:'second_largest([4, 9, 2, 7]) → 7\nsecond_largest([10, 5, 8])   → 8',tests:[{args:[[4,9,2,7]],expected:7},{args:[[10,5,8]],expected:8},{args:[[1,9,3,7]],expected:7}]}]},
  { id:'search', tag:'CORE OPERATION', title:'Search an array', objective:'Find whether a value exists and return its position using linear search.', duration:'14 min lesson', body:`<h3>Ask one element at a time</h3><p>Linear search checks each value from left to right until it finds the target. It works whether the array is sorted or unsorted.</p><pre class="code-snippet">numbers = [6, 3, 11, 8]\ntarget = 11\n\nfor index in range(len(numbers)):\n    if numbers[index] == target:\n        print(index)  <span class="comment"># 2</span>\n        break</pre><h4>Best and worst cases</h4><ul><li>If the target is first, the search can finish immediately.</li><li>If the target is last or missing, we inspect every value.</li><li>The worst-case time complexity is O(n).</li></ul>`, code:`numbers = [6, 3, 11, 8]\ntarget = 11\n\nfor index in range(len(numbers)):\n    if numbers[index] == target:\n        print(index)\n        break`, output:'2', problems:[{id:'linear_search',title:'Return the target index',difficulty:'EASY',description:'Return the index of target in nums. Return -1 if target does not exist.',hint:'Loop over indexes with range(len(nums)). Return as soon as nums[index] equals target.',functionName:'linear_search',starter:'def linear_search(nums, target):\n    # Return the index, or -1\n    pass',examples:'linear_search([4, 8, 2], 8) → 1\nlinear_search([4, 8, 2], 7) → -1',tests:[{args:[[4,8,2],8],expected:1},{args:[[4,8,2],7],expected:-1},{args:[[5],5],expected:0}]}]},
  { id:'reverse', tag:'PATTERN', title:'Reverse an array', objective:'Reverse values in place and learn the two-pointer pattern.', duration:'18 min lesson', body:`<h3>Two pointers, moving inward</h3><p>Place one pointer at the beginning and one at the end. Swap those values, move both pointers inward, and stop when they meet.</p><pre class="code-snippet">numbers = [1, 2, 3, 4]\nleft, right = 0, len(numbers) - 1\n\nwhile left &lt; right:\n    numbers[left], numbers[right] = numbers[right], numbers[left]\n    left += 1\n    right -= 1\n\nprint(numbers)  <span class="comment"># [4, 3, 2, 1]</span></pre><div class="concept-callout"><strong>In place</strong><p>We change the original array instead of creating a second array. That keeps extra space at O(1).</p></div>`, code:`numbers = [1, 2, 3, 4]\nleft, right = 0, len(numbers) - 1\n\nwhile left < right:\n    numbers[left], numbers[right] = numbers[right], numbers[left]\n    left += 1\n    right -= 1\n\nprint(numbers)`, output:'[4, 3, 2, 1]', problems:[{id:'reverse_array',title:'Reverse in place',difficulty:'EASY',description:'Reverse nums in place and return the same array.',hint:'Use left and right indexes. Swap the values, then move left forward and right backward.',functionName:'reverse_array',starter:'def reverse_array(nums):\n    # Reverse nums in place and return it\n    pass',examples:'reverse_array([1, 2, 3]) → [3, 2, 1]\nreverse_array([7, 4])    → [4, 7]',tests:[{args:[[1,2,3]],expected:[3,2,1]},{args:[[7,4]],expected:[4,7]},{args:[[]],expected:[]}]}]},
  { id:'prefix', tag:'PATTERN', title:'Prefix sums', objective:'Precompute running totals so repeated range-sum questions become fast.', duration:'18 min lesson', body:`<h3>Store the work you have already done</h3><p>A prefix sum array stores the total from the beginning up to each position. Once it is built, a range sum can be answered with a subtraction.</p><pre class="code-snippet">numbers = [2, 4, 1, 5]\nprefix = [0]\n\nfor number in numbers:\n    prefix.append(prefix[-1] + number)\n\nprint(prefix)  <span class="comment"># [0, 2, 6, 7, 12]</span></pre><p>The prefix array takes O(n) time to build. Each range-sum query after that takes O(1).</p><div class="concept-callout"><strong>Formula</strong><p>Sum from index left to right = prefix[right + 1] - prefix[left].</p></div>`, code:`numbers = [2, 4, 1, 5]\nprefix = [0]\n\nfor number in numbers:\n    prefix.append(prefix[-1] + number)\n\nprint(prefix)`, output:'[0, 2, 6, 7, 12]', problems:[{id:'running_sum',title:'Build a running sum',difficulty:'EASY',description:'Return an array where answer[i] is the sum of nums[0] through nums[i].',hint:'Keep a running total. Append the updated total after processing each number.',functionName:'running_sum',starter:'def running_sum(nums):\n    # Return the running sums\n    pass',examples:'running_sum([1, 2, 3]) → [1, 3, 6]\nrunning_sum([5, 5])    → [5, 10]',tests:[{args:[[1,2,3]],expected:[1,3,6]},{args:[[5,5]],expected:[5,10]},{args:[[]],expected:[]}]}]},
  { id:'twopointer', tag:'PATTERN', title:'Two pointers', objective:'Use two moving indexes to solve pair and comparison problems efficiently.', duration:'20 min lesson', body:`<h3>Two viewpoints, one scan</h3><p>The two-pointer pattern is useful when an array is sorted or when the problem compares values from opposite ends. Instead of trying every pair, move the pointer that can improve the answer.</p><pre class="code-snippet">numbers = [1, 2, 4, 7, 11]\ntarget = 9\nleft, right = 0, len(numbers) - 1\n\nwhile left &lt; right:\n    total = numbers[left] + numbers[right]\n    if total == target:\n        print(left, right)\n        break\n    if total &lt; target:\n        left += 1\n    else:\n        right -= 1</pre><p>On a sorted array this can reduce a pair search from O(n²) to O(n).</p>`, code:`numbers = [1, 2, 4, 7, 11]\ntarget = 9\nleft, right = 0, len(numbers) - 1\n\nwhile left < right:\n    total = numbers[left] + numbers[right]\n    if total == target:\n        print([left, right])\n        break\n    if total < target:\n        left += 1\n    else:\n        right -= 1`, output:'[1, 3]', problems:[{id:'two_sum_sorted',title:'Two sum in a sorted array',difficulty:'EASY',description:'Return the indexes of two values in sorted nums that add up to target. Return [-1, -1] if there is no pair.',hint:'If the sum is too small, move left forward. If it is too large, move right backward.',functionName:'two_sum_sorted',starter:'def two_sum_sorted(nums, target):\n    # Return two indexes\n    pass',examples:'two_sum_sorted([1, 2, 4, 7], 9) → [1, 3]\ntwo_sum_sorted([1, 3, 5], 20) → [-1, -1]',tests:[{args:[[1,2,4,7],9],expected:[1,3]},{args:[[1,3,5],20],expected:[-1,-1]},{args:[[2,4],6],expected:[0,1]}]}]},
  { id:'rotate', tag:'CHALLENGE', title:'Rotate an array', objective:'Combine slicing, indexes, and careful thinking about positions to rotate values.', duration:'20 min lesson', body:`<h3>Positions shift in a circle</h3><p>Rotating right by one moves the final value to the front. A rotation by k positions can be simplified using <code>k % len(nums)</code>.</p><pre class="code-snippet">numbers = [1, 2, 3, 4, 5]\nk = 2\nk = k % len(numbers)\nrotated = numbers[-k:] + numbers[:-k]\nprint(rotated)  <span class="comment"># [4, 5, 1, 2, 3]</span></pre><div class="concept-callout"><strong>Watch the edge case</strong><p>If k is larger than the array length, reduce it first. If the array is empty, there is nothing to rotate.</p></div>`, code:`numbers = [1, 2, 3, 4, 5]\nk = 2\nk = k % len(numbers)\nrotated = numbers[-k:] + numbers[:-k]\nprint(rotated)`, output:'[4, 5, 1, 2, 3]', problems:[{id:'rotate_right',title:'Rotate right by k',difficulty:'MEDIUM',description:'Return nums rotated to the right by k positions.',hint:'Reduce k using k % len(nums), then combine the last k values with the remaining prefix.',functionName:'rotate_right',starter:'def rotate_right(nums, k):\n    # Return nums rotated right by k\n    pass',examples:'rotate_right([1, 2, 3, 4, 5], 2) → [4, 5, 1, 2, 3]\nrotate_right([1, 2], 3)       → [2, 1]',tests:[{args:[[1,2,3,4,5],2],expected:[4,5,1,2,3]},{args:[[1,2],3],expected:[2,1]},{args:[[],4],expected:[]}]}]}
];

const extraProblems = {
  intro: [
    {id:'sum_array',title:'Sum all values',difficulty:'EASY',description:'Return the sum of every value in nums.',hint:'Start total at zero and add each number as you traverse the array.',functionName:'sum_array',starter:'def sum_array(nums):\n    # Return the sum\n    pass',examples:'sum_array([2, 4, 6]) → 12\nsum_array([])          → 0',tests:[{args:[[2,4,6]],expected:12},{args:[[]],expected:0},{args:[[-2,5]],expected:3}]},
    {id:'count_positive',title:'Count positive values',difficulty:'EASY',description:'Return how many values in nums are greater than zero.',hint:'Use a counter and increase it only when the current value is greater than zero.',functionName:'count_positive',starter:'def count_positive(nums):\n    # Return the count of positive values\n    pass',examples:'count_positive([-2, 4, 0, 7]) → 2\ncount_positive([-1, 0])       → 0',tests:[{args:[[-2,4,0,7]],expected:2},{args:[[-1,0]],expected:0},{args:[[1,2,3]],expected:3}]},
    {id:'contains_value',title:'Check whether a value exists',difficulty:'EASY',description:'Return True if target appears in nums; otherwise return False.',hint:'Traverse the array and return True as soon as you find target.',functionName:'contains_value',starter:'def contains_value(nums, target):\n    # Return True or False\n    pass',examples:'contains_value([3, 8, 1], 8) → True\ncontains_value([3, 8, 1], 5) → False',tests:[{args:[[3,8,1],8],expected:true},{args:[[3,8,1],5],expected:false},{args:[[],1],expected:false}]},
    {id:'product_array',title:'Product of all values',difficulty:'EASY',description:'Return the product of every value in nums. Return 1 for an empty array.',hint:'Initialize product to 1, then multiply it by each value.',functionName:'product_array',starter:'def product_array(nums):\n    # Return the product\n    pass',examples:'product_array([2, 3, 4]) → 24\nproduct_array([])       → 1',tests:[{args:[[2,3,4]],expected:24},{args:[[]],expected:1},{args:[[-2,5]],expected:-10}]}
  ],
  traverse: [
    {id:'count_greater',title:'Count values above a target',difficulty:'EASY',description:'Return how many values in nums are strictly greater than target.',hint:'Compare each value with target and increment a counter when the comparison is true.',functionName:'count_greater',starter:'def count_greater(nums, target):\n    # Return the count\n    pass',examples:'count_greater([2, 8, 4, 9], 5) → 2\ncount_greater([1, 2], 2)       → 0',tests:[{args:[[2,8,4,9],5],expected:2},{args:[[1,2],2],expected:0},{args:[[5,5,5],4],expected:3}]},
    {id:'last_index',title:'Find the last index',difficulty:'EASY',description:'Return the last index where target appears in nums, or -1 when it is missing.',hint:'Keep updating the answer whenever you find target instead of returning immediately.',functionName:'last_index',starter:'def last_index(nums, target):\n    # Return the last matching index\n    pass',examples:'last_index([4, 2, 4, 7], 4) → 2\nlast_index([1, 3], 5)       → -1',tests:[{args:[[4,2,4,7],4],expected:2},{args:[[1,3],5],expected:-1},{args:[[6],6],expected:0}]},
    {id:'is_sorted',title:'Check if an array is sorted',difficulty:'EASY',description:'Return True if nums is in non-decreasing order.',hint:'Compare every value with the value immediately before it.',functionName:'is_sorted',starter:'def is_sorted(nums):\n    # Return True when nums is sorted\n    pass',examples:'is_sorted([1, 2, 2, 5]) → True\nis_sorted([1, 4, 3])   → False',tests:[{args:[[1,2,2,5]],expected:true},{args:[[1,4,3]],expected:false},{args:[[]],expected:true}]},
    {id:'move_zeroes',title:'Move zeroes to the end',difficulty:'EASY',description:'Return nums with all zeroes moved to the end while keeping the order of non-zero values.',hint:'Build the non-zero values first, then add the required number of zeroes.',functionName:'move_zeroes',starter:'def move_zeroes(nums):\n    # Return the rearranged array\n    pass',examples:'move_zeroes([0, 1, 0, 3, 12]) → [1, 3, 12, 0, 0]\nmove_zeroes([0, 0])             → [0, 0]',tests:[{args:[[0,1,0,3,12]],expected:[1,3,12,0,0]},{args:[[0,0]],expected:[0,0]},{args:[[1,2]],expected:[1,2]}]}
  ],
  maxmin: [
    {id:'minimum_value',title:'Find the minimum value',difficulty:'EASY',description:'Return the smallest value in a non-empty array.',hint:'Start with nums[0] as the smallest value and update it when you see a smaller number.',functionName:'minimum_value',starter:'def minimum_value(nums):\n    # Return the minimum\n    pass',examples:'minimum_value([4, 9, 2, 7]) → 2\nminimum_value([-3, -1])     → -3',tests:[{args:[[4,9,2,7]],expected:2},{args:[[-3,-1]],expected:-3},{args:[[5]],expected:5}]},
    {id:'range_difference',title:'Difference between max and min',difficulty:'EASY',description:'Return the largest value minus the smallest value in nums.',hint:'Track both extremes in one pass, then subtract minimum from maximum.',functionName:'range_difference',starter:'def range_difference(nums):\n    # Return max(nums) - min(nums)\n    pass',examples:'range_difference([4, 9, 2, 7]) → 7\nrange_difference([-3, 2])     → 5',tests:[{args:[[4,9,2,7]],expected:7},{args:[[-3,2]],expected:5},{args:[[8]],expected:0}]},
    {id:'max_subarray_sum',title:'Maximum subarray sum',difficulty:'MEDIUM',description:'Return the largest sum of a non-empty contiguous subarray.',hint:'Use Kadane’s idea: keep the best sum ending at the current position and the best answer so far.',functionName:'max_subarray_sum',starter:'def max_subarray_sum(nums):\n    # Return the best contiguous sum\n    pass',examples:'max_subarray_sum([-2, 1, -3, 4, -1, 2, 1, -5, 4]) → 6\nmax_subarray_sum([-3, -1]) → -1',tests:[{args:[[-2,1,-3,4,-1,2,1,-5,4]],expected:6},{args:[[-3,-1]],expected:-1},{args:[[5,-2,3]],expected:6}]},
    {id:'third_largest',title:'Third largest distinct value',difficulty:'MEDIUM',description:'Return the third largest distinct value. The input contains at least three distinct values.',hint:'Track the top three distinct values while scanning, or build a set and sort it.',functionName:'third_largest',starter:'def third_largest(nums):\n    # Return the third largest distinct value\n    pass',examples:'third_largest([4, 9, 2, 7, 9]) → 4\nthird_largest([10, 5, 8, 3])   → 5',tests:[{args:[[4,9,2,7,9]],expected:4},{args:[[10,5,8,3]],expected:5},{args:[[1,4,2,3]],expected:2}]}
  ],
  search: [
    {id:'binary_search',title:'Binary search',difficulty:'EASY',description:'Return the index of target in sorted nums, or -1 if it is missing.',hint:'Use left and right boundaries. Compare the middle value and discard half the search space.',functionName:'binary_search',starter:'def binary_search(nums, target):\n    # Return the target index\n    pass',examples:'binary_search([1, 3, 5, 7], 5) → 2\nbinary_search([1, 3, 5, 7], 4) → -1',tests:[{args:[[1,3,5,7],5],expected:2},{args:[[1,3,5,7],4],expected:-1},{args:[[2],2],expected:0}]},
    {id:'search_insert',title:'Search insert position',difficulty:'EASY',description:'Return the index where target is found or should be inserted to keep nums sorted.',hint:'Binary search for the first position whose value is greater than or equal to target.',functionName:'search_insert',starter:'def search_insert(nums, target):\n    # Return the correct position\n    pass',examples:'search_insert([1, 3, 5, 6], 5) → 2\nsearch_insert([1, 3, 5, 6], 2) → 1',tests:[{args:[[1,3,5,6],5],expected:2},{args:[[1,3,5,6],2],expected:1},{args:[[1,3,5,6],7],expected:4}]},
    {id:'count_sorted',title:'Count a target in sorted nums',difficulty:'EASY',description:'Return how many times target appears in sorted nums.',hint:'A simple scan works first. You can later optimize by finding the first and last positions with binary search.',functionName:'count_sorted',starter:'def count_sorted(nums, target):\n    # Return the frequency\n    pass',examples:'count_sorted([1, 2, 2, 2, 4], 2) → 3\ncount_sorted([1, 3], 2)       → 0',tests:[{args:[[1,2,2,2,4],2],expected:3},{args:[[1,3],2],expected:0},{args:[[5,5],5],expected:2}]},
    {id:'find_peak',title:'Find a peak index',difficulty:'EASY',description:'Return an index of any value that is not smaller than its neighbors. The ends have only one neighbor.',hint:'Compare each value with its left and right neighbors. Return the first valid peak.',functionName:'find_peak',starter:'def find_peak(nums):\n    # Return an index of a peak\n    pass',examples:'find_peak([1, 3, 2]) → 1\nfind_peak([5])       → 0',tests:[{args:[[1,3,2]],expected:1},{args:[[5]],expected:0},{args:[[2,1,3,4]],expected:3}]}
  ],
  reverse: [
    {id:'array_palindrome',title:'Check array palindrome',difficulty:'EASY',description:'Return True if nums reads the same from left to right and right to left.',hint:'Compare values at matching positions from the two ends.',functionName:'array_palindrome',starter:'def array_palindrome(nums):\n    # Return True or False\n    pass',examples:'array_palindrome([1, 2, 1]) → True\narray_palindrome([1, 2, 3]) → False',tests:[{args:[[1,2,1]],expected:true},{args:[[1,2,3]],expected:false},{args:[[]],expected:true}]},
    {id:'merge_sorted',title:'Merge two sorted arrays',difficulty:'EASY',description:'Return one sorted array containing all values from a and b.',hint:'Use two indexes and append the smaller current value, then append leftovers.',functionName:'merge_sorted',starter:'def merge_sorted(a, b):\n    # Return one sorted array\n    pass',examples:'merge_sorted([1, 3], [2, 4]) → [1, 2, 3, 4]\nmerge_sorted([], [2, 5])   → [2, 5]',tests:[{args:[[1,3],[2,4]],expected:[1,2,3,4]},{args:[[],[2,5]],expected:[2,5]},{args:[[1,2],[]],expected:[1,2]}]},
    {id:'remove_duplicates_sorted',title:'Remove duplicates from sorted nums',difficulty:'EASY',description:'Return a new array containing each value from sorted nums only once.',hint:'Append a value only when the result is empty or its last value is different.',functionName:'remove_duplicates_sorted',starter:'def remove_duplicates_sorted(nums):\n    # Return unique values\n    pass',examples:'remove_duplicates_sorted([1, 1, 2, 3, 3]) → [1, 2, 3]\nremove_duplicates_sorted([])          → []',tests:[{args:[[1,1,2,3,3]],expected:[1,2,3]},{args:[[]],expected:[]},{args:[[4,4,4]],expected:[4]}]},
    {id:'reverse_groups',title:'Reverse every group of k',difficulty:'MEDIUM',description:'Return nums with each complete group of k values reversed. Leave a shorter final group unchanged.',hint:'Walk in steps of k and reverse each slice. Be careful with the final incomplete group.',functionName:'reverse_groups',starter:'def reverse_groups(nums, k):\n    # Return groups reversed\n    pass',examples:'reverse_groups([1,2,3,4,5], 2) → [2,1,4,3,5]\nreverse_groups([1,2,3], 3)   → [3,2,1]',tests:[{args:[[1,2,3,4,5],2],expected:[2,1,4,3,5]},{args:[[1,2,3],3],expected:[3,2,1]},{args:[[1,2],4],expected:[1,2]}]}
  ],
  prefix: [
    {id:'build_prefix',title:'Build prefix sums',difficulty:'EASY',description:'Return an array where each position stores the sum from the beginning through that position.',hint:'Keep a running total and append it after each value.',functionName:'build_prefix',starter:'def build_prefix(nums):\n    # Return prefix sums\n    pass',examples:'build_prefix([2, 4, 1]) → [2, 6, 7]\nbuild_prefix([])       → []',tests:[{args:[[2,4,1]],expected:[2,6,7]},{args:[[]],expected:[]},{args:[[-2,5]],expected:[-2,3]}]},
    {id:'range_sum',title:'Answer a range sum',difficulty:'EASY',description:'Return the sum of nums from index left through index right, inclusive.',hint:'For this version, a loop is enough. Then think about how prefix sums could answer it faster.',functionName:'range_sum',starter:'def range_sum(nums, left, right):\n    # Return the inclusive range sum\n    pass',examples:'range_sum([2, 4, 1, 5], 1, 3) → 10\nrange_sum([2, 4, 1], 0, 1)       → 6',tests:[{args:[[2,4,1,5],1,3],expected:10},{args:[[2,4,1],0,1],expected:6},{args:[[7],0,0],expected:7}]},
    {id:'pivot_index',title:'Find the pivot index',difficulty:'EASY',description:'Return the first index where the sum on the left equals the sum on the right. Return -1 if none exists.',hint:'Use the total sum. At each index, right sum equals total minus left sum minus nums[i].',functionName:'pivot_index',starter:'def pivot_index(nums):\n    # Return the first pivot index\n    pass',examples:'pivot_index([1, 7, 3, 6, 5, 6]) → 3\npivot_index([1, 2, 3])          → -1',tests:[{args:[[1,7,3,6,5,6]],expected:3},{args:[[1,2,3]],expected:-1},{args:[[2,1,-1]],expected:0}]},
    {id:'even_odd_difference',title:'Difference of even and odd sums',difficulty:'EASY',description:'Return the sum of even values minus the sum of odd values.',hint:'Maintain two totals while traversing the array, then subtract the odd total.',functionName:'even_odd_difference',starter:'def even_odd_difference(nums):\n    # Return even sum - odd sum\n    pass',examples:'even_odd_difference([1, 2, 3, 4]) → 2\neven_odd_difference([5, 7])       → -12',tests:[{args:[[1,2,3,4]],expected:2},{args:[[5,7]],expected:-12},{args:[[]],expected:0}]}
  ],
  twopointer: [
    {id:'container_water',title:'Container with most water',difficulty:'MEDIUM',description:'Return the maximum area formed by two vertical lines represented by heights.',hint:'Start at both ends. Move the pointer with the shorter height because keeping it cannot improve the area.',functionName:'container_water',starter:'def container_water(heights):\n    # Return the maximum area\n    pass',examples:'container_water([1,8,6,2,5,4,8,3,7]) → 49\ncontainer_water([1,1])                 → 1',tests:[{args:[[1,8,6,2,5,4,8,3,7]],expected:49},{args:[[1,1]],expected:1},{args:[[4,3,2,1,4]],expected:16}]},
    {id:'remove_value',title:'Remove a value in place',difficulty:'EASY',description:'Remove every occurrence of value from nums and return the resulting array.',hint:'Use a write position and copy only values that are not equal to value.',functionName:'remove_value',starter:'def remove_value(nums, value):\n    # Return nums without value\n    pass',examples:'remove_value([3, 2, 2, 3], 3) → [2, 2]\nremove_value([1, 2], 4)       → [1, 2]',tests:[{args:[[3,2,2,3],3],expected:[2,2]},{args:[[1,2],4],expected:[1,2]},{args:[[5,5],5],expected:[]}]},
    {id:'three_sum_zero',title:'Find a zero-sum triplet',difficulty:'MEDIUM',description:'Return True if three distinct values in nums add up to zero; otherwise return False.',hint:'Sort the array. Fix one value, then use two pointers for the remaining pair.',functionName:'three_sum_zero',starter:'def three_sum_zero(nums):\n    # Return True or False\n    pass',examples:'three_sum_zero([-1, 0, 1, 2, -1]) → True\nthree_sum_zero([1, 2, 3])           → False',tests:[{args:[[-1,0,1,2,-1]],expected:true},{args:[[1,2,3]],expected:false},{args:[[0,0,0]],expected:true}]}
  ],
  rotate: [
    {id:'rotate_left',title:'Rotate left by k',difficulty:'EASY',description:'Return nums rotated to the left by k positions.',hint:'Reduce k by the array length, then join the slice after k with the slice before k.',functionName:'rotate_left',starter:'def rotate_left(nums, k):\n    # Return nums rotated left\n    pass',examples:'rotate_left([1,2,3,4,5], 2) → [3,4,5,1,2]\nrotate_left([1,2], 3)       → [2,1]',tests:[{args:[[1,2,3,4,5],2],expected:[3,4,5,1,2]},{args:[[1,2],3],expected:[2,1]},{args:[[],4],expected:[]}]},
    {id:'is_rotation',title:'Check if one array is a rotation',difficulty:'EASY',description:'Return True if b can be produced by rotating a any number of positions.',hint:'Two arrays must have equal lengths. A rotation appears inside a + a.',functionName:'is_rotation',starter:'def is_rotation(a, b):\n    # Return True or False\n    pass',examples:'is_rotation([1,2,3], [2,3,1]) → True\nis_rotation([1,2], [2,1])   → True',tests:[{args:[[1,2,3],[2,3,1]],expected:true},{args:[[1,2],[2,1]],expected:true},{args:[[1,2],[1,2,3]],expected:false}]},
    {id:'rotate_one',title:'Rotate right by one',difficulty:'EASY',description:'Return nums after moving its final value to the front.',hint:'The last value is nums[-1]. Combine it with all values except the last.',functionName:'rotate_one',starter:'def rotate_one(nums):\n    # Return nums rotated right once\n    pass',examples:'rotate_one([1,2,3]) → [3,1,2]\nrotate_one([])       → []',tests:[{args:[[1,2,3]],expected:[3,1,2]},{args:[[]],expected:[]},{args:[[8]],expected:[8]}]}
  ]
};
lessons.forEach(lesson=>{ lesson.problems.push(...(extraProblems[lesson.id]||[])); });

const state = { current:0, completed:JSON.parse(localStorage.getItem('arraylab_completed')||'[]'), problem:null };
const $ = id => document.getElementById(id);
const currentLesson = () => lessons[state.current];
function allProblems(){ return lessons.flatMap(l=>l.problems); }
function saveProgress(){ localStorage.setItem('arraylab_completed', JSON.stringify(state.completed)); }
function renderSidebar(){ $('lessonList').innerHTML=lessons.map((l,i)=>`<button class="lesson-item ${i===state.current?'active ':''}${state.completed.includes(l.id)?'completed':''}" data-index="${i}"><span class="lesson-num">${String(i+1).padStart(2,'0')}</span><span class="lesson-name">${l.title}</span><span class="lesson-check">✓</span></button>`).join(''); document.querySelectorAll('.lesson-item').forEach(b=>b.addEventListener('click',()=>{state.current=Number(b.dataset.index);state.problem=null;render()})); const percent=Math.round(state.completed.length/lessons.length*100); $('progressPercent').textContent=percent+'%';$('progressFill').style.width=percent+'%';$('completedCount').textContent=`${state.completed.length} of ${lessons.length} lessons`; }
function render(){ const l=currentLesson(); $('lessonTag').textContent=l.tag; $('lessonTitle').textContent=l.title; $('lessonObjective').textContent=l.objective; $('lessonDuration').textContent=l.duration; $('lessonBody').innerHTML=l.body; $('currentIndex').textContent=String(state.current+1).padStart(2,'0'); $('completeButton').classList.toggle('is-complete',state.completed.includes(l.id)); $('completeButton').innerHTML=state.completed.includes(l.id)?'Completed <span>✓</span>':'Mark complete <span>✓</span>'; $('previousButton').disabled=state.current===0; $('nextButton').innerHTML=state.current===lessons.length-1?'Finish module <span>✓</span>':'Next lesson <span>→</span>'; $('codeEditor').value=l.code; $('output').textContent='Run the example to see the output.'; $('runStatus').textContent='Ready'; renderProblems(l);renderSidebar(); }
function renderProblems(l){$('problemCount').textContent=`${l.problems.length} problem${l.problems.length===1?'':'s'}`; $('problemList').hidden=!!state.problem; $('problemWorkspace').hidden=!state.problem; if(!state.problem){$('problemList').innerHTML=l.problems.map((p,i)=>`<div class="problem-row" data-problem="${p.id}"><div class="problem-icon">${i+1}</div><div><h4>${p.title}</h4><p>${p.description}</p></div><span class="problem-meta">${p.difficulty}</span></div>`).join('');document.querySelectorAll('.problem-row').forEach(row=>row.addEventListener('click',()=>openProblem(row.dataset.problem)));return}const p=state.problem;$('problemDifficulty').textContent=p.difficulty;$('problemTitle').textContent=p.title;$('problemDescription').textContent=p.description;$('problemHint').textContent=p.hint;$('problemExamples').textContent=p.examples;$('problemEditor').value=p.starter;$('submissionResult').textContent='Your result will appear here.';$('submissionResult').className='submission-result'; }
function openProblem(id){state.problem=currentLesson().problems.find(p=>p.id===id);renderProblems(currentLesson());window.scrollTo({top:document.querySelector('.problem-section').offsetTop-20,behavior:'smooth'});}
function showToast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
const runner=new Worker('pyodide-worker.js');let jobId=0;const jobs=new Map();runner.onmessage=({data})=>{const job=jobs.get(data.id);if(!job)return;if(data.output)job.output+=data.output;if(data.error)job.error=data.error;if(!data.done)return;clearTimeout(job.timer);jobs.delete(data.id);if(job.mode==='run')job.resolve({ok:data.ok&&!job.error,output:job.output,error:job.error||data.error});else job.resolve(data);};function runInBrowser(payload){return new Promise((resolve,reject)=>{const id=++jobId;const mode=payload.mode;const timer=setTimeout(()=>{jobs.delete(id);reject(new Error('Execution timed out.'))},10000);jobs.set(id,{resolve,reject,mode,output:'',error:'',timer});runner.postMessage({...payload,id});});}
$('runButton').addEventListener('click',async()=>{ $('runStatus').textContent='Loading Python…';$('output').textContent='';try{const result=await runInBrowser({mode:'run',code:$('codeEditor').value});$('output').textContent=result.output||result.error||'(no output)';$('runStatus').textContent=result.ok?'Done':'Error';}catch(e){$('output').textContent='The browser Python runner timed out. Refresh and try again.';$('runStatus').textContent='Offline';}});
$('resetCode').addEventListener('click',()=>{$('codeEditor').value=currentLesson().code;$('output').textContent='Run the example to see the output.';$('runStatus').textContent='Ready';});
$('completeButton').addEventListener('click',()=>{const id=currentLesson().id;if(!state.completed.includes(id)){state.completed.push(id);saveProgress();renderSidebar();$('completeButton').classList.add('is-complete');$('completeButton').innerHTML='Completed <span>✓</span>';showToast('Lesson completed — nice work!');}else{state.completed=state.completed.filter(x=>x!==id);saveProgress();render();}});
$('previousButton').addEventListener('click',()=>{if(state.current>0){state.current--;state.problem=null;render();window.scrollTo({top:0,behavior:'smooth'});}});$('nextButton').addEventListener('click',()=>{if(state.current<lessons.length-1){state.current++;state.problem=null;render();window.scrollTo({top:0,behavior:'smooth'});}else{showToast('You finished the Array module!');}});
$('closeProblem').addEventListener('click',()=>{state.problem=null;renderProblems(currentLesson());});
$('submitButton').addEventListener('click',async()=>{if(!state.problem)return;const box=$('submissionResult');box.className='submission-result';box.textContent='Loading Python and checking your solution…';try{const result=await runInBrowser({mode:'check',code:$('problemEditor').value,functionName:state.problem.functionName,tests:state.problem.tests});if(result.ok){box.className='submission-result success';box.textContent=`All tests passed — ${result.passed}/${result.total} cases correct.`;showToast('Problem solved!');}else{box.className='submission-result error';box.textContent=result.message||result.error||`You passed ${result.passed}/${result.total} tests. Read the hint and try again.`;}}catch(e){box.className='submission-result error';box.textContent='The browser Python runner timed out. Refresh and try again.';}});
$('resetProgress').addEventListener('click',()=>{if(confirm('Reset all ArrayLab progress?')){state.completed=[];saveProgress();render();showToast('Progress reset.');}});
render();
